### ISSUE TITLE
$env:Path isn't updated correctly to reflect new versions

### ISSUE THREAD

**Issue by D-Bullock** [robert-j-engdahl/ngettext-wpf#21]
In the Package Manager Console type: `$env:Path`.

Below is an excerpt from my path variable
> C:\Users\Office1\.nuget\packages\ngettext.wpf\1.0.18-alpha\tools;C:\Users\Office1\.nuget\packages\gettext.tools\0.19.8.1\tools;C:\Users\Office1\.nuget\packages\gettext.tools\0.19.8.1\tools\bin;C:\Users\Office1\.nuget\packages\ngettext.wpf\1.0.21-alpha\tools

You'll notice that there's both .18 and .21 listed as versions

**Comment by robert-j-engdahl** [comment]
It is nice to have these issues rooted out.

This is a problem, because the older version will appear sooner in the `$Env:Path`.

Restarting the package manager console works around the issue.

I agree that we should at least update the $Env:Path in a way that the most recent `XGetText-Xaml.ps1` is the one invoked when typing the command.

**Comment by robert-j-engdahl** [comment]
It appears this happens only because we have anything in the tools directory.  We do not modify the path ourselves.   See for instance: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package (scroll down to the description of the tools directory).

It seems clear that this is a nuget issue.  So I created one here: https://github.com/NuGet/Home/issues/7353

So we have a work-around and we have identified the source of the error to be outside this project.
