### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by D-Bullock** [robert-j-engdahl/ngettext-wpf#24]
I'd like to have more comments, and I notice in #9 you talk about using noop to define "please store a translation of this string" 
Is there any other reason to use a noop? I'll go and create a merge request with some extra comments after you respond.

**Comment by robert-j-engdahl** [comment]
Are you thinking of comments for the translator?

But no, noop is a no-operation, named after the one available in GNU gettext.  It's purpose is solely to mark a string for translation.  The trick is that you want the actual translation to be postponed until the last possible moment, so that the right language is used.  One case for this is actually the feature I am working on just now for work; where permissions are discovered on run-time and stored in a database so they can later be granted via some user management workspace.  The permission includes a msgid marked with noop, which enables the strings read back from the database (on another machine, on another date with another language selected) to be translated.

Anyway, I am missing the context of this question, so my reply above may not be too useful.

**Comment by D-Bullock** [comment]
I just meant in code comments for the Translation file. Your answer gives me everything I need.
