### ISSUE TITLE
Mute the Translation not found for message id error messages

### ISSUE THREAD

**Issue by D-Bullock** [robert-j-engdahl/ngettext-wpf#44]
Is it possible to mute the messages NGettext: Translation not found for message id?
They are useful when checking for coverage - but when you're using  the default (english) then it fires for every single translation attempt.

**Comment by robert-j-engdahl** [comment]
I agree, there should be no spam.

**Comment by robert-j-engdahl** [comment]
Oh, this is printed by NGettext and not NGettext.Wpf.  I'll check if they have some option to suppress this.

**Comment by robert-j-engdahl** [comment]
It's here (not in our code):

https://github.com/VitaliiTsilnyk/NGettext/blob/a701ac67a9822f71539ac7f81d671d6281790c9d/src/NGettext/Catalog.cs#L286

No options to disable it.

If you create an English .po file and load it into PoEdit, you can do CTRL+B while selecting all, to have them all return their msgids.

I also think the NGettext authors are happy to accept issues and pull requests :)

Anyway, since this issue is in a component build by a different organization, I'm closing this issue.  We can continue the conversation in here anyway :)

**Comment by D-Bullock** [comment]
I didn't even think to check there - I was scratching my head trying to work out where the writeline was coming from. Thanks for the tip with POEdit - I'll use that to get rid of the spam

**Comment by robert-j-engdahl** [comment]
I recreated the issue here https://github.com/VitaliiTsilnyk/NGettext/issues/28

**Comment by robert-j-engdahl** [comment]
@VitaliiTsilnyk agrees and will fix this very soon (according to the above linked issue thread)
